---
abstract: 'Get contacts/addressbook from Web'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0.90
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Contact
provides:
  WWW::Contact:
    file: lib/WWW/Contact.pm
    version: 0.48
  WWW::Contact::AOL:
    file: lib/WWW/Contact/AOL.pm
    version: 0.47
  WWW::Contact::BG::Abv:
    file: lib/WWW/Contact/BG/Abv.pm
    version: 0.26
  WWW::Contact::BG::Mail:
    file: lib/WWW/Contact/BG/Mail.pm
    version: 0.26
  WWW::Contact::Base:
    file: lib/WWW/Contact/Base.pm
    version: 0.16
  WWW::Contact::CN::163:
    file: lib/WWW/Contact/CN/163.pm
    version: 0.28
  WWW::Contact::Gmail:
    file: lib/WWW/Contact/Gmail.pm
    version: 0.24
  WWW::Contact::GoogleContactsAPI:
    file: lib/WWW/Contact/GoogleContactsAPI.pm
    version: 0.44
  WWW::Contact::GoogleContactsAPIOAuth2:
    file: lib/WWW/Contact/GoogleContactsAPIOAuth2.pm
    version: 0.001
  WWW::Contact::Hotmail:
    file: lib/WWW/Contact/Hotmail.pm
    version: 0.46
  WWW::Contact::Indiatimes:
    file: lib/WWW/Contact/Indiatimes.pm
    version: 0.16
  WWW::Contact::Lycos:
    file: lib/WWW/Contact/Lycos.pm
    version: 0.16
  WWW::Contact::Mail:
    file: lib/WWW/Contact/Mail.pm
    version: 0.16
  WWW::Contact::Plaxo:
    file: lib/WWW/Contact/Plaxo.pm
    version: 0.16
  WWW::Contact::Rediffmail:
    file: lib/WWW/Contact/Rediffmail.pm
    version: 0.30
  WWW::Contact::Yahoo:
    file: lib/WWW/Contact/Yahoo.pm
    version: 0.46
requires:
  Crypt::SSLeay: 0
  HTML::Entities: 0
  HTML::TokeParser::Simple: 0
  HTML::TreeBuilder: 0
  JSON::XS: 0
  Moose: 0.77
  Net::DNS::Resolver: 0
  Net::Google::AuthSub: 0
  Text::vCard: 0
  WWW::Mechanize: 0
  WWW::Mechanize::GZip: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/fayland/perl-www-contact/tree/master
version: 0.48
